DROP DATABASE IF EXISTS [WSTowersOffice];

CREATE DATABASE [WSTowersOffice];

USE [WSTowersOffice];
GO

CREATE TABLE [File] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[FileType] INT NOT NULL,
[FileName] VARCHAR(300) UNIQUE NOT NULL,
[Width] INTEGER NULL,
[Height] INTEGER NULL,
[Leaght] INTEGER NOT NULL
);
INSERT INTO [File] ([FileType], [FileName], [Leaght]) VALUES (1,'default_team_icon.png',32768);
INSERT INTO [File] ([FileType], [FileName], [Leaght]) VALUES (3,'default_employee_icon.png',32768);

CREATE TABLE [Team] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) UNIQUE NOT NULL,
[Icon] INTEGER NOT NULL,
[Description] VARCHAR(1000) NULL,
FOREIGN KEY ([Icon]) REFERENCES [File]([ID])
);

CREATE TABLE [Role](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Name] VARCHAR(100) UNIQUE NOT NULL,
[Icon] INTEGER NOT NULL,
[Description] VARCHAR(1000) NULL,
FOREIGN KEY ([Icon]) REFERENCES [File]([ID])
);

CREATE TABLE [Team_Role](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Team] INTEGER NOT NULL,
[Role] INTEGER NOT NULL,
FOREIGN KEY ([Team]) REFERENCES [Team]([ID]),
FOREIGN KEY ([Role]) REFERENCES [Role]([ID])
);

CREATE TABLE [Employee] (
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[CPF] VARCHAR(15) UNIQUE NOT NULL,
[Name] VARCHAR(500) NOT NULL,
[QuantityFamilyPersons] INT NOT NULL,
[Email] VARCHAR(1000) UNIQUE NOT NULL,
[ProfileImage] INTEGER NOT NULL,
FOREIGN KEY ([ProfileImage]) REFERENCES [File]([ID])
);

CREATE TABLE [Team_Employee](
[ID] INTEGER PRIMARY KEY IDENTITY NOT NULL,
[Team] INTEGER NOT NULL,
[Employee] INTEGER NOT NULL,
[AddDate] DATETIME NOT NULL,
[Role] INTEGER NOT NULL,
FOREIGN KEY ([Team]) REFERENCES [Team]([ID]),
FOREIGN KEY ([Employee]) REFERENCES [Employee]([ID]),
FOREIGN KEY ([Role]) REFERENCES [Team_Role]([ID])
);

CREATE TABLE [Login] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[UserName] VARCHAR(100) UNIQUE NOT NULL,
[Password] VARCHAR(200) NOT NULL,
[Email] VARCHAR(300) UNIQUE NOT NULL,
[isValidEmail] BIT NOT NULL,
[ValidKey] VARCHAR(86)  UNIQUE NOT NULL,
[CreateDate] DATETIME NOT NULL
);

CREATE TABLE [IP] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[IP] VARCHAR(89) UNIQUE NOT NULL,
[Confiance] INT NOT NULL,
[AlreadyBeenBanned] BIT NOT NULL
);

CREATE TABLE [Authentication] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[User-Agent] VARCHAR(300) NOT NULL,
[IP] VARCHAR(89) NOT NULL,
[Token] VARCHAR(86) UNIQUE NOT NULL,
[Login] INTEGER NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([Login]) REFERENCES [Login]([ID]),
FOREIGN KEY ([IP]) REFERENCES [IP]([IP])
);