#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WSTowersOffice.App.Resource", IsApplication=true)]

namespace WSTowersOffice.App
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int fab_margin = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int branca = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int branco = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int logo = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int logo_azul = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int logo_pb = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int logo_training = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int logo_verde = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int round_button = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int selo = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int ws = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int ws_towers_office = 2130903050;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int action_settings = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int buttonLogin = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int buttonRegister = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int logoImg = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int txtWork = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_splash = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int activity_start = 2131034113;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int menu_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int action_settings = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int start_login = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int start_new_user = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int start_text = 2131230724;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme_NoActionBar = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
