//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowersOffice.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public int ID { get; set; }
        public string User_Agent { get; set; }
        public string IP { get; set; }
        public string Token { get; set; }
        public int Login { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Login Login1 { get; set; }
    }
}
