//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowersOffice.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IP
    {
        public int ID { get; set; }
        public string IP1 { get; set; }
        public int Confiance { get; set; }
        public bool AlreadyBeenBanned { get; set; }
    }
}
