//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTowersOffice.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team_Role()
        {
            this.Team_Employee = new HashSet<Team_Employee>();
        }
    
        public int ID { get; set; }
        public int Team { get; set; }
        public int Role { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_Employee> Team_Employee { get; set; }
    }
}
